#include <Include/PiDxe.h>
#include "pci_type.h"

/* PCI registers for D14F3 */
#define LPC_PCI_CONTROL			0x40
#define   LEGACY_DMA_EN			BIT2
#define   VW_ROM_SHARING_EN		BIT3
#define   EXT_ROM_SHARING_EN		BIT4

#define LPC_IO_PORT_DECODE_ENABLE	0x44
#define   DECODE_ENABLE_PARALLEL_PORT0	BIT0
#define   DECODE_ENABLE_PARALLEL_PORT1	BIT1
#define   DECODE_ENABLE_PARALLEL_PORT2	BIT2
#define   DECODE_ENABLE_PARALLEL_PORT3	BIT3
#define   DECODE_ENABLE_PARALLEL_PORT4	BIT4
#define   DECODE_ENABLE_PARALLEL_PORT5	BIT5
#define   DECODE_ENABLE_SERIAL_PORT0	BIT6
#define   DECODE_ENABLE_SERIAL_PORT1	BIT7
#define   DECODE_ENABLE_SERIAL_PORT2	BIT8
#define   DECODE_ENABLE_SERIAL_PORT3	BIT9
#define   DECODE_ENABLE_SERIAL_PORT4	BIT10
#define   DECODE_ENABLE_SERIAL_PORT5	BIT11
#define   DECODE_ENABLE_SERIAL_PORT6	BIT12
#define   DECODE_ENABLE_SERIAL_PORT7	BIT13
#define   DECODE_ENABLE_AUDIO_PORT0	BIT14
#define   DECODE_ENABLE_AUDIO_PORT1	BIT15
#define   DECODE_ENABLE_AUDIO_PORT2	BIT16
#define   DECODE_ENABLE_AUDIO_PORT3	BIT17
#define   DECODE_ENABLE_MIDI_PORT0	BIT18
#define   DECODE_ENABLE_MIDI_PORT1	BIT19
#define   DECODE_ENABLE_MIDI_PORT2	BIT20
#define   DECODE_ENABLE_MIDI_PORT3	BIT21
#define   DECODE_ENABLE_MSS_PORT0	BIT22
#define   DECODE_ENABLE_MSS_PORT1	BIT23
#define   DECODE_ENABLE_MSS_PORT2	BIT24
#define   DECODE_ENABLE_MSS_PORT3	BIT25
#define   DECODE_ENABLE_FDC_PORT0	BIT26
#define   DECODE_ENABLE_FDC_PORT1	BIT27
#define   DECODE_ENABLE_GAME_PORT	BIT28
#define   DECODE_ENABLE_KBC_PORT	BIT29
#define   DECODE_ENABLE_ACPIUC_PORT	BIT30
#define   DECODE_ENABLE_ADLIB_PORT	BIT31

#define LPC_IO_OR_MEM_DECODE_ENABLE	0x48
#define   LPC_WIDEIO2_ENABLE		BIT25
#define   LPC_WIDEIO1_ENABLE		BIT24
#define   DECODE_IO_PORT_ENABLE6	BIT23
#define   DECODE_IO_PORT_ENABLE5	BIT22
#define   DECODE_IO_PORT_ENABLE4	BIT21
#define   DECODE_MEM_PORT_ENABLE1	BIT20
#define   DECODE_IO_PORT_ENABLE3	BIT19
#define   DECODE_IO_PORT_ENABLE2	BIT18
#define   DECODE_IO_PORT_ENABLE1	BIT17
#define   DECODE_IO_PORT_ENABLE0	BIT16
#define   LPC_SYNC_TIMEOUT_COUNT_MASK	(0xff << 8)
#define   LPC_SYNC_TIMEOUT_COUNT_ENABLE	BIT7
#define   LPC_DECODE_RTC_IO_ENABLE	BIT6
#define   DECODE_MEM_PORT_ENABLE0	BIT5
#define   LPC_WIDEIO0_ENABLE		BIT2
#define   DECODE_ALTERNATE_SIO_ENABLE	BIT1
#define   DECODE_SIO_ENABLE		BIT0
#define     LPC_SELECT_SIO_4E4F		1
#define     LPC_SELECT_SIO_2E2F		0
#define   WIDEIO_RANGE_ERROR		-1

/* Assuming word access to higher word (register 0x4a) */
#define LPC_IO_OR_MEM_DEC_EN_HIGH	0x4a
#define   LPC_WIDEIO2_ENABLE_H		BIT9
#define   LPC_WIDEIO1_ENABLE_H		BIT8
#define   DECODE_IO_PORT_ENABLE6_H	BIT7
#define   DECODE_IO_PORT_ENABLE5_H	BIT6
#define   DECODE_IO_PORT_ENABLE4_H	BIT5
#define   DECODE_IO_PORT_ENABLE3_H	BIT3
#define   DECODE_IO_PORT_ENABLE2_H	BIT2
#define   DECODE_IO_PORT_ENABLE1_H	BIT1
#define   DECODE_IO_PORT_ENABLE0_H	BIT0

#define LPC_MEM_PORT1			0x4c
#define ROM_PROTECT_RANGE0		0x50
#define   ROM_BASE_MASK			0xfffff000		/* bits 31-12 */
#define   ROM_RANGE_WP			BIT10
#define   ROM_RANGE_RP			BIT9
#define   RANGE_UNIT			BIT8
#define   RANGE_ADDR_MASK		0x000000ff		/* Range defined by bits 7-0 */
#define ROM_PROTECT_RANGE_REG(n)	(ROM_PROTECT_RANGE0 + (4 * n))
#define MAX_ROM_PROTECT_RANGES		4
#define LPC_MEM_PORT0			0x60

/* Register 0x64 is 32-bit, composed by two 16-bit sub-registers.
   For ease of access, each sub-register is declared separately. */
#define LPC_WIDEIO_GENERIC_PORT		0x64
#define LPC_WIDEIO1_GENERIC_PORT	0x66
#define ROM_ADDRESS_RANGE1_START	0x68
#define ROM_ADDRESS_RANGE1_END		0x6a
#define ROM_ADDRESS_RANGE2_START	0x6c
#define ROM_ADDRESS_RANGE2_END		0x6e

#define LPC_ALT_WIDEIO_RANGE_ENABLE	0x74
#define   LPC_ALT_WIDEIO2_ENABLE	BIT3
#define   LPC_ALT_WIDEIO1_ENABLE	BIT2
#define   LPC_ALT_WIDEIO0_ENABLE	BIT0

#define LPC_MISC_CONTROL_BITS		0x78
#define   LPC_NOHOG			BIT0

#define LPC_TRUSTED_PLATFORM_MODULE	0x7c
#define   TPM_12_EN			BIT0
#define   TPM_LEGACY_EN			BIT2

#define LPC_WIDEIO2_GENERIC_PORT	0x90

#define SPIROM_BASE_ADDRESS_REGISTER	0xa0
#define SPI_BASE_ALIGNMENT		BIT6
#define   SPI_BASE_RESERVED		(BIT4 | BIT5)
#define   ROUTE_TPM_2_SPI		BIT3
#define   SPI_ABORT_ENABLE		BIT2
#define   SPI_ROM_ENABLE		BIT1
#define   SPI_ROM_ALT_ENABLE		BIT0
#define   SPI_PRESERVE_BITS		(BIT0 | BIT1 | BIT2 | BIT3)

/* LPC register 0xb8 is DWORD, here there are definitions for byte
   access. For example, bits 31-24 are accessed through byte access
   at register 0xbb. */
#define LPC_ROM_DMA_EC_HOST_CONTROL	0xb8
#define   SPI_FROM_HOST_PREFETCH_EN	BIT24
#define   SPI_FROM_USB_PREFETCH_EN	BIT23

#define LPC_HOST_CONTROL		0xbb
#define   PREFETCH_EN_SPI_FROM_HOST	BIT0
#define   T_START_ENH			BIT3

#define _LPCB_DEV PCI_DEV(0, 0x14, 0x3)

unsigned long int lpc_get_spibase(void);
